trigger: none

pool:
  vmImage: 'ubuntu-18.04'

parameters:
- name: scenario
  displayName: NeoLoad Scenario
  type: string
  default: sanityTOSCA
  values:
  - sanityTOSCA
  - fullTOSCA
- name: duration
  displayName: Test Duration (Mins)
  type: number
  default: 2
- name: vus
  displayName: Test VUs (as License Permits)
  type: number
  default: 5
- name: max_sla_failure_percent
  displayName: Max SLA Failure Percent (0-100)
  type: number
  default: 25

variables:
  neoloadToken: $(secret_nlw_token)
  neoloadApiUrl: 'https://neoload-web-api.neotys.perfreleng.org/'
  workspaceId: '5fd12022430f780001e3fb61'
  zoneId: 'wNBKe'
  PYTHONUNBUFFERED: 1

jobs:
- job: RunLoadTest
  displayName: Run NeoLoad Test from Azure Devops
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'

  - task: Bash@3
    displayName: Install NeoLoad
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        echo "Installing NeoLoad from Pypi Live (~20sec); if you don't want to do this, bake the NeoLoad CLI in!"
        pip install -q neoload==1.3.0.dev5
        neoload --version

  - task: Bash@3
    displayName: Configure the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        DYN_SCENARIO_FILE=$(Build.SourcesDirectory)/actual-scenario.yaml
        cp yaml/scenario.template $DYN_SCENARIO_FILE
        sed -i 's/\[\[max_users\]\]/${{ parameters.vus }}/g' $DYN_SCENARIO_FILE
        sed -i 's/\[\[max_duration\]\]/${{ parameters.duration }}m/g' $DYN_SCENARIO_FILE

        cat ./actual-scenario.yaml

        neoload validate .

        neoload login --url $(neoloadApiUrl) --workspace $(workspaceId) $(neoloadToken) \
                test-settings --zone $(zoneId) --lgs 1 --scenario ${{ parameters.scenario }} createorpatch "TOSCANeoLoadFromAzure" \
                project --path $(Build.SourcesDirectory) upload "TOSCANeoLoadFromAzure"

  - task: Bash@3
    displayName: Run the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload run --name "TOSCANeoLoadFromAzure_$(Build.BuildNumber)" \
                    --description "Azure example with meta; $(Build.BuildUri)" \
                    --scenario ${{ parameters.scenario }} \
                    --as-code actual-scenario.yaml,yaml/slas.template.nl.yaml \
                    --detached
        sleep 10

  - task: Bash@3
    displayName: Wait for fastfail or finish signals
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        { sleep 120; neoload fastfail --max-failure ${{ parameters.max_sla_failure_percent }} slas cur; } &
        neoload wait cur

  - task: Bash@3
    displayName: Get the junit SLA report
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
       neoload test-results --junit-file $(Common.TestResultsDirectory)/neoload-slas.xml junitsla

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true
