trigger: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
  neoloadToken: $(secret_nlw_token)
  neoloadApiUrl: 'https://neoload-api.saas.neotys.com/'
  workspaceId: '5f329c43f6ecb40001d7b3e2'
  zoneId: 'fNCnQ'
  max_fail_percent: 25
  PYTHONUNBUFFERED: 1

jobs:
- job: RunLoadTest
  displayName: Run NeoLoad Test from Azure Devops
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'

  - task: Bash@3
    displayName: Install NeoLoad
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        pip install neoload==1.3.0.dev2
        neoload --version

  - task: Bash@3
    displayName: Configure the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload login --url $(neoloadApiUrl) --workspace $(workspaceId) $(neoloadToken) \
                test-settings --zone $(zoneId) --scenario fullTOSCA createorpatch "TOSCANeoLoadFromAzure" \
                project --path $(Build.SourcesDirectory) upload "TOSCANeoLoadFromAzure"

  - task: Bash@3
    displayName: Run the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload run --name "TOSCANeoLoadFromAzure_$(Build.BuildNumber)" \
                    --description "Azure example with meta; $(Build.BuildUri)" \
                    --detached
        sleep 10

  - task: Bash@3
    displayName: Wait for fastfail or finish signals
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        { sleep 120; neoload fastfail --max-failure $(max_fail_percent) slas cur; } &
        neoload wait cur

  - task: Bash@3
    displayName: Get the junit SLA report
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
       neoload test-results --junit-file $(Common.TestResultsDirectory)/neoload-slas.xml junitsla

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true
